import {useEffect,useState} from 'react';
import {Activity, ArrowRight, ArrowUpRight, Bell, Check, ChevronRight, CircleDollarSign, CreditCard, FileText, Globe2, LayoutDashboard, Link2, Menu, Plus, Search, Settings, ShieldCheck, Sparkles, Users, WalletCards, X} from 'lucide-react';

type View='Overview'|'Transactions'|'Payment links'|'Invoices'|'Customers';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const transactions=[
 {id:'XP-84291',customer:'Horizon Ability Group',service:'ADA consulting retainer',date:'Jul 14, 2026',amount:2400,status:'Paid'},
 {id:'XP-84290',customer:'Maya Richardson',service:'AI strategy session',date:'Jul 13, 2026',amount:650,status:'Paid'},
 {id:'XP-84289',customer:'Northline Legal',service:'Expert witness deposit',date:'Jul 12, 2026',amount:3200,status:'Pending'},
 {id:'XP-84288',customer:'Carter Studios',service:'CL360 Music license',date:'Jul 11, 2026',amount:480,status:'Paid'},
];
const nav:[View,any][]=[['Overview',LayoutDashboard],['Transactions',Activity],['Payment links',Link2],['Invoices',FileText],['Customers',Users]];

function App(){
 if(window.location.pathname==='/xpay'||window.location.pathname==='/xpay/') return <XPayLanding/>;
 const [view,setView]=useState<View>('Overview'); const [menu,setMenu]=useState(false); const [modal,setModal]=useState(false); const [notice,setNotice]=useState('');
 const [apiReady,setApiReady]=useState<boolean|null>(null); const [creating,setCreating]=useState(false); const [paymentTitle,setPaymentTitle]=useState('Strategy consultation'); const [paymentAmount,setPaymentAmount]=useState('500');
 useEffect(()=>{fetch('/api/health').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(()=>setApiReady(true)).catch(()=>setApiReady(false))},[]);
 const select=(v:View)=>{setView(v);setMenu(false)};
 const createLink=async()=>{setCreating(true);try{const response=await fetch('/api/payment-links',{method:'POST',headers:{'Content-Type':'application/json','x-demo-role':'admin'},body:JSON.stringify({title:paymentTitle,amount:Math.round(Number(paymentAmount)*100)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to create link');setModal(false);setNotice(data.mode==='stripe_test'?'Stripe test checkout created.':'Simulated payment link created — no live charge was made.')}catch(error){setNotice(error instanceof Error?error.message:'The API could not create the payment link.')}finally{setCreating(false);setTimeout(()=>setNotice(''),5000)}};
 return <div className="app">
  <a className="skip" href="#main">Skip to main content</a>
  <aside className={menu?'sidebar open':'sidebar'} aria-label="Primary navigation">
   <div className="brand-row"><a className="brand brand-link" href="https://www.cl360ai.com" aria-label="CareerLift360 home"><div className="mark">x</div><div><b>CL360 <span>xPay</span></b><small>BY CAREERLIFT360 LLC</small></div></a><button className="mobile-close" onClick={()=>setMenu(false)} aria-label="Close navigation"><X/></button></div>
   <nav>{nav.map(([n,I])=><button key={n} className={view===n?'active':''} onClick={()=>select(n)}><I size={19}/><span>{n}</span>{n==='Invoices'&&<i>3</i>}</button>)}</nav>
   <div className="nav-bottom"><a href="https://www.cl360ai.com"><Globe2 size={19}/><span>CL360AI.com</span><ArrowUpRight size={14}/></a><button><Sparkles size={19}/><span>Business CFO</span><em>AI</em></button><button><Settings size={19}/><span>Settings</span></button></div>
   <div className="security"><ShieldCheck/><div><b>{apiReady===false?'API offline':'Live mode active'}</b><small>{apiReady===null?'Checking secure API…':apiReady?'API connected · payments simulated':'Start npm run dev'}</small></div></div>
  </aside>
  <section className="shell">
   <header><button className="menu" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><div className="search"><Search size={18}/><input aria-label="Search" placeholder="Search payments, customers…"/><kbd>⌘ K</kbd></div><div className="header-actions"><span className="test-dot">TEST MODE</span><button aria-label="Notifications"><Bell size={20}/><i/></button><div className="avatar">DR</div><div className="user"><b>Dr. Riggins</b><small>Administrator</small></div></div></header>
   <main id="main">
    {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
    <div className="welcome"><div><p className="eyebrow">CL360 xPAY WORKSPACE</p><h1>{view==='Overview'?'Good afternoon, Dr. Riggins.':view}</h1><p>{view==='Overview'?'Here’s how CareerLift360 is moving today.':'Manage your '+view.toLowerCase()+' in a secure test workspace.'}</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> Create payment</button></div>
    <div className="sandbox"><ShieldCheck size={19}/><span><b>{apiReady===false?'Dashboard preview mode.':'Production workspace.'}</b> {apiReady===false?'Start the API to create test records.':'No real funds can move from this workspace.'}</span><a href="https://www.cl360ai.com">CL360AI.com <ArrowUpRight size={15}/></a></div>
    {view==='Overview'?<Overview onCreate={()=>setModal(true)}/>:<DataView view={view}/>} 
    <footer><span>© 2026 CareerLift360 LLC</span><a href="https://www.cl360ai.com">www.cl360ai.com</a><nav><a href="https://www.cl360ai.com">CareerLift360 home</a><a href="#security">Security</a><a href="#privacy">Privacy</a></nav></footer>
   </main>
  </section>
  {modal&&<div className="backdrop" onMouseDown={()=>setModal(false)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setModal(false)} aria-label="Close"><X/></button><p className="eyebrow">SANDBOX</p><h2 id="modal-title">Create a payment link</h2><p>Share a professional checkout for a service, deposit, or digital product.</p><label>Payment title<input value={paymentTitle} onChange={e=>setPaymentTitle(e.target.value)} required/></label><div className="row"><label>Amount<input type="number" min="0.5" step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} required/></label><label>Currency<select defaultValue="USD"><option>USD</option></select></label></div><label>Description<textarea defaultValue="60-minute CareerLift360 consultation"/></label><button className="primary wide" onClick={createLink} disabled={creating||!paymentTitle||Number(paymentAmount)<.5}>{creating?'Creating securely…':'Create test link'} {!creating&&<ChevronRight size={18}/>}</button><small className="fine">Creates a simulated checkout. Stripe test credentials are required for hosted Checkout.</small></div></div>}
 </div>
}

function XPayLanding(){return <div className="landing">
 <header className="landing-nav"><a className="brand brand-link" href="https://www.cl360ai.com"><div className="mark">x</div><div><b>CL360 <span>xPay</span></b><small>BY CAREERLIFT360 LLC</small></div></a><nav><a href="#solutions">Solutions</a><a href="#security">Security</a><a href="#about">About</a></nav><div><a className="site-link" href="https://www.cl360ai.com">CL360AI.com <ArrowUpRight size={14}/></a><a className="primary" href="/">Open sandbox</a></div></header>
 <main><section className="hero"><div className="hero-copy"><p className="landing-pill"><Sparkles size={14}/> AI-powered payment operations</p><h1>Every payment.<br/><span>One intelligent workspace.</span></h1><p>CL360 xPay helps consultants, creators, ADA service providers, expert witnesses, and music professionals manage how they get paid—without losing sight of the business behind every transaction.</p><div className="hero-actions"><a className="primary" href="/">Explore the sandbox <ArrowRight size={17}/></a><a className="outline" href="#solutions">See how it works</a></div><div className="trust-row"><span><Check/> Test-mode first</span><span><Check/> Provider-hosted checkout</span><span><Check/> Accessible by design</span></div></div><DashboardPreview/></section>
 <section className="proof"><p>BUILT FOR THE CAREERLIFT360 ECOSYSTEM</p><div><span>AI Consulting</span><span>ADA Services</span><span>Expert Witness</span><span>CL360 Music</span><span>Creators</span></div></section>
 <section className="landing-section" id="solutions"><div className="section-intro"><p className="eyebrow">ONE OPERATING LAYER</p><h2>From invoice to insight.</h2><p>Professional payment workflows connected to the financial intelligence of CL360 Business CFO™.</p></div><div className="feature-grid"><Feature icon={<Link2/>} title="Shareable payment links" text="Create polished sandbox checkouts for retainers, sessions, licenses, and digital services."/><Feature icon={<FileText/>} title="Invoices that stay organized" text="Track drafts, due dates, balances, and customer history from one workspace."/><Feature icon={<Activity/>} title="A clear transaction view" text="See payment activity and provider status without exposing sensitive card data."/><Feature icon={<Sparkles/>} title="Business CFO intelligence" text="Prepare for cash-flow analysis, reconciliation, forecasting, and tax-ready reporting."/></div></section>
 <section className="security-section" id="security"><div><p className="eyebrow">SECURITY BY DEFAULT</p><h2>Built to start safely.</h2><p>The MVP remains in sandbox mode until verified processor credentials and production controls are supplied. CL360 xPay is payment-operations software—not a bank, cryptocurrency, or money transmitter.</p></div><ul><li><ShieldCheck/><span><b>Test credentials only</b>Live Stripe keys are rejected by the MVP.</span></li><li><ShieldCheck/><span><b>No card-data storage</b>Checkout is designed for provider-hosted collection.</span></li><li><ShieldCheck/><span><b>Optional modules stay off</b>PayPal and stablecoin rails require explicit review and configuration.</span></li></ul></section>
 <section className="cta" id="about"><div><p className="eyebrow">A CAREERLIFT360 LLC PRODUCT</p><h2>Business without payment chaos.</h2><p>See the working CL360 xPay test environment and explore the next generation of AI-powered payment operations.</p></div><a className="primary" href="/">Enter the sandbox <ArrowRight size={17}/></a></section></main>
 <footer className="landing-footer"><a className="brand brand-link" href="https://www.cl360ai.com"><div className="mark">x</div><div><b>CL360 <span>xPay</span></b><small>BY CAREERLIFT360 LLC</small></div></a><p>© 2026 CareerLift360 LLC · <a href="https://www.cl360ai.com">www.cl360ai.com</a></p><p>No affiliation with X Corp. No proprietary token.</p></footer>
 </div>}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <article><div>{icon}</div><h3>{title}</h3><p>{text}</p><a href="/">View in sandbox <ArrowRight size={14}/></a></article>}
function DashboardPreview(){return <div className="hero-preview"><div className="preview-top"><span><i/> CL360 xPay</span><em>TEST MODE</em></div><div className="preview-body"><p>Gross volume</p><strong>$6,730.00</strong><span className="preview-up">↑ 12.4% this month</span><div className="mini-chart"><i/><i/><i/><i/><i/><i/><i/></div><div className="preview-cards"><span><small>Successful</small><b>48</b></span><span><small>Customers</small><b>36</b></span></div></div><div className="float-card"><ShieldCheck/><span><b>Sandbox secured</b><small>No real funds move</small></span></div></div>}

function Overview({onCreate}:{onCreate:()=>void}){return <>
 <section className="metrics" aria-label="Payment metrics">
  <article><div><span>Gross volume</span><CircleDollarSign/></div><strong>{money(6730)}</strong><p><b>↑ 12.4%</b> from last month</p></article>
  <article><div><span>Successful payments</span><CreditCard/></div><strong>48</strong><p><b>↑ 8.2%</b> from last month</p></article>
  <article><div><span>Outstanding invoices</span><FileText/></div><strong>{money(3850)}</strong><p><em>3 invoices</em> need attention</p></article>
  <article><div><span>Active customers</span><Users/></div><strong>36</strong><p><b>↑ 4</b> new this month</p></article>
 </section>
 <section className="grid">
  <article className="panel activity-panel"><div className="panel-head"><div><h2>Revenue activity</h2><p>Payment volume over the last 7 days</p></div><select aria-label="Revenue date range"><option>Last 7 days</option></select></div><div className="chart"><div className="ylabels"><span>$2k</span><span>$1.5k</span><span>$1k</span><span>$500</span><span>$0</span></div><svg viewBox="0 0 700 220" role="img" aria-label="Revenue rises from Monday through Sunday"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7c5cff" stopOpacity=".25"/><stop offset="1" stopColor="#7c5cff" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 170 C60 160 75 125 130 135 S210 170 265 120 S360 80 410 100 S510 145 555 70 S640 55 700 20 L700 220 L0 220Z"/><path className="line" d="M0 170 C60 160 75 125 130 135 S210 170 265 120 S360 80 410 100 S510 145 555 70 S640 55 700 20"/></svg><div className="xlabels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></article>
  <article className="panel quick"><div className="panel-head"><div><h2>Quick actions</h2><p>Move work forward</p></div></div><button onClick={onCreate}><span><Link2/></span><div><b>Payment link</b><small>Create a shareable checkout</small></div><ChevronRight/></button><button><span><FileText/></span><div><b>New invoice</b><small>Bill a client professionally</small></div><ChevronRight/></button><button><span><Users/></span><div><b>Add customer</b><small>Build your client directory</small></div><ChevronRight/></button><button><span><WalletCards/></span><div><b>Payment methods</b><small>Configure test providers</small></div><ChevronRight/></button></article>
 </section>
 <section className="panel tx"><div className="panel-head"><div><h2>Recent transactions</h2><p>Your latest payment activity</p></div><button>View all <ArrowUpRight size={15}/></button></div><TransactionTable/></section>
 <section className="ai-card"><div className="ai-icon"><Sparkles/></div><div><p className="eyebrow">CL360 BUSINESS CFO™</p><h2>Your AI finance copilot is ready.</h2><p>Connect transaction events to cash-flow insights, reconciliation workflows, and tax-ready summaries.</p></div><button>Explore integration <ArrowUpRight size={16}/></button></section>
 </>}

function TransactionTable(){return <div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Customer</th><th>Service</th><th>Date</th><th>Status</th><th>Amount</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td><b>{t.id}</b></td><td>{t.customer}</td><td>{t.service}</td><td>{t.date}</td><td><span className={'status '+t.status.toLowerCase()}>{t.status}</span></td><td><b>{money(t.amount)}</b></td></tr>)}</tbody></table></div>}
type ApiRecord={id:string;name?:string;email?:string;company?:string;number?:string;customerName?:string;title?:string;amount?:number;status?:string;url?:string;createdAt:string};
function DataView({view}:{view:View}){const [records,setRecords]=useState<ApiRecord[]>([]);const [loading,setLoading]=useState(false);const [showForm,setShowForm]=useState(false);const [error,setError]=useState('');const endpoint=view==='Customers'?'customers':view==='Invoices'?'invoices':view==='Payment links'?'payment-links':'';
 const load=()=>{if(!endpoint)return;setLoading(true);fetch(`/api/${endpoint}`,{headers:{'x-demo-role':'admin'}}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setRecords(d.data||[])).catch(()=>setError('Start the API to load sandbox records.')).finally(()=>setLoading(false))};
 useEffect(load,[endpoint]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const body=endpoint==='customers'?{name:form.get('name'),email:form.get('email'),company:form.get('company')}:endpoint==='invoices'?{customerName:form.get('customerName'),amount:Math.round(Number(form.get('amount'))*100),dueAt:form.get('dueAt')}:{title:form.get('title'),amount:Math.round(Number(form.get('amount'))*100)};const response=await fetch(`/api/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json','x-demo-role':'admin'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){setError(data.error||'Unable to save record');return}setError('');setShowForm(false);load()};
 if(view==='Transactions')return <section className="panel data-view"><div className="panel-head"><div><h2>Transactions</h2><p>Sandbox records for your CareerLift360 workspace</p></div></div><TransactionTable/></section>;
 return <section className="panel data-view"><div className="panel-head"><div><h2>{view}</h2><p>API-backed sandbox records for your CareerLift360 workspace</p></div><button className="secondary" onClick={()=>setShowForm(v=>!v)}><Plus size={16}/> New</button></div>
 {showForm&&<form className="inline-form" onSubmit={submit}>{endpoint==='customers'?<><label>Name<input name="name" required minLength={2}/></label><label>Email<input name="email" type="email" required/></label><label>Company<input name="company"/></label></>:endpoint==='invoices'?<><label>Customer<input name="customerName" required/></label><label>Amount<input name="amount" type="number" min=".5" step=".01" required/></label><label>Due date<input name="dueAt" type="date"/></label></>:<><label>Payment title<input name="title" required/></label><label>Amount<input name="amount" type="number" min=".5" step=".01" required/></label></>}<button className="primary" type="submit">Save test record</button></form>}
 {error&&<p className="form-error" role="alert">{error}</p>}{loading?<div className="empty"><p>Loading secure records…</p></div>:records.length?<div className="record-list">{records.map(record=><article key={record.id}><div>{view==='Customers'?<Users/>:view==='Invoices'?<FileText/>:<Link2/>}</div><span><b>{record.name||record.number||record.title}</b><small>{record.email||record.customerName||record.url||'Sandbox record'}</small></span>{typeof record.amount==='number'&&<strong>{money(record.amount/100)}</strong>}<em>{record.status||'Active'}</em></article>)}</div>:<div className="empty"><div>{view==='Invoices'?<FileText/>:view==='Customers'?<Users/>:<Link2/>}</div><h3>Your {view.toLowerCase()} will live here</h3><p>Create your first record to preview the complete sandbox workflow.</p><button className="primary" onClick={()=>setShowForm(true)}><Plus size={17}/> Create {view.replace(/s$/,'')}</button></div>}</section>}
export default App;
